### ISSUE TITLE
What is Key.py in .gitignore for ?

### ISSUE THREAD

**Issue by rohittm** [SIMRAN88/instaBot#1]

**Comment by SIMRAN88** [comment]
It is for the key.py file that uses the API Key

**Comment by rohittm** [comment]
But if it is not pushed, how will the app work.

**Comment by rohittm** [comment]
you can give some kind of template and tell your viewers how to add the key 🥇

**Comment by SIMRAN88** [comment]
Yes,I have to do that.
Because the user has to generate their own access token for the bot and they cannot access mine. @rohittm

**Comment by SIMRAN88** [comment]
It is being pushed and the app will work fine because the key is not used directly but imported from key.py.
